### ISSUE TITLE
Remove Useless / Unused Code

### ISSUE THREAD

**Issue by jinlucky** [Helder1981/OneForAll#1]
### You have instance of 
- Mandelbrot (Andrew Duncan)
- Game of Life

**Comment by withgallantry** [comment]
This is because it's a direct copy of the library, it's being updated to a symlink.

**Comment by jinlucky** [comment]
You maybe check your license. You have many library from other developer.

**Comment by withgallantry** [comment]
Yes, as stated it’s going to be updated to a symlink and the library is
also covered by an MIT license that states its free to use for our use
case. Your input is valued but please try and validate your issues before
adding them. The license is a non issue and therefore did not need
mentioning.
